### ISSUE TITLE
Crash in Admin

### ISSUE THREAD

**Issue by Keda87** [loftylabs/django-developer-panel#4]
Hi, thank you for the awesome work!
I've tested your work but, suddenly my project crash when opening django admin.
Here is the stacktrace.
```
File "/Users/adiyatmubarak/.pyenv/versions/2.7.13/lib/python2.7/site-packages/djdev_panel/middleware.py", line 19, in <module>
    from django.urls import resolve
ImportError: No module named urls
```
I'm using python `2.7.13` and `Django (1.9.6)`

**Comment by ckinsey** [comment]
This issue was fixed in django-developer-panel-0.1.2, please update your copy!
