### ISSUE TITLE
Image (logo?) doesn't work

### ISSUE THREAD

**Issue by LaurensBosscher** [loftylabs/django-developer-panel#8]
https://camo.githubusercontent.com/314a20f80be1aeda7e7db463beb824c9db73b21a/687474703a2f2f686972656c6f6674792e636f6d2f6d656469612f696d616765732f53637265656e5f53686f745f323031372d30352d31325f61745f352e32302e33305f504d2e77696474682d3830302e706e67

returns a 404

**Comment by ckinsey** [comment]
Good catch, I updated the URL for that image (it's a screen shot of the panel)
